# Generated by Django 5.2.7 on 2025-10-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_moviequote_remove_quote_movie_delete_movie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviequote',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moviequote',
            name='submitted_by',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
